"""Public model aggregator for the template-aligned backend app.

Keep imports from this package stable. API routes and tests should continue to
use ``from app.models import User, ProjectPublic`` while table definitions live
in focused modules.
"""

from app.models.assets import (
    Asset,
    AssetBase,
    AssetContextImportPublic,
    AssetCreate,
    AssetPublic,
    AssetRecalculatePublic,
    AssetsPublic,
    AssetUpdate,
    Component,
    ComponentBase,
)
from app.models.attack import (
    AttackTactic,
    AttackTacticBase,
    AttackTacticPublic,
    AttackTechnique,
    AttackTechniqueBase,
    AttackTechniquePublic,
    CveAttackMapping,
    CveAttackMappingBase,
    CveAttackMappingPublic,
    FindingAttackContext,
    FindingAttackContextBase,
    FindingAttackContextPublic,
    ProjectAttackSummaryPublic,
    ProjectAttackTacticSummaryPublic,
    ProjectAttackTechniqueSummaryPublic,
)
from app.models.auth import Token, TokenPayload
from app.models.decisions import (
    FindingExplanationPublic,
    ProjectCvssOnlyComparisonPublic,
    ProjectDecisionSummaryPublic,
)
from app.models.enums import (
    AnalysisRunStatus,
    AssetCriticality,
    AssetEnvironment,
    AssetExposure,
    FindingPriority,
    FindingStatus,
)
from app.models.findings import (
    Finding,
    FindingAttackContextDetailPublic,
    FindingAttackMappingDetailPublic,
    FindingAttackTechniqueDetailPublic,
    FindingBase,
    FindingDetailPublic,
    FindingOccurrencePublic,
    FindingPublic,
    FindingsPublic,
)
from app.models.governance import (
    GovernanceRollupPublic,
    GovernanceWaiverDebtEntryPublic,
    GovernanceWaiverDebtPublic,
    ProjectGovernanceRollupsPublic,
)
from app.models.projects import (
    Project,
    ProjectBase,
    ProjectCreate,
    ProjectPublic,
    ProjectsPublic,
    ProjectUpdate,
)
from app.models.providers import (
    ProviderSnapshotStatusPublic,
    ProviderSourceStatusPublic,
    ProviderStatusPublic,
    ProviderUpdateJobPublic,
)
from app.models.registry import import_table_models
from app.models.reports import (
    Report,
    ReportBase,
    ReportCreate,
    ReportPublic,
    ReportsPublic,
    ReportVerificationPublic,
)
from app.models.runs import (
    AnalysisRun,
    AnalysisRunBase,
    AnalysisRunPublic,
    AnalysisRunsPublic,
    AnalysisRunSummaryPublic,
    FindingOccurrence,
    FindingOccurrenceBase,
    ImportParseErrorPublic,
    ProviderSnapshot,
    ProviderSnapshotBase,
)
from app.models.users import User, UserBase, UserPublic, UsersPublic
from app.models.vulnerabilities import Vulnerability, VulnerabilityBase
from app.models.waivers import (
    Waiver,
    WaiverBase,
    WaiverCreate,
    WaiverPublic,
    WaiversPublic,
    WaiverUpdate,
)
from app.models.workbench import MigrationStatus, WorkbenchStatus

__all__ = [
    "AnalysisRun",
    "AnalysisRunBase",
    "AnalysisRunPublic",
    "AnalysisRunSummaryPublic",
    "AnalysisRunsPublic",
    "AnalysisRunStatus",
    "Asset",
    "AssetBase",
    "AssetContextImportPublic",
    "AssetCriticality",
    "AssetCreate",
    "AssetEnvironment",
    "AssetExposure",
    "AssetPublic",
    "AssetRecalculatePublic",
    "AssetsPublic",
    "AssetUpdate",
    "AttackTactic",
    "AttackTacticBase",
    "AttackTacticPublic",
    "AttackTechnique",
    "AttackTechniqueBase",
    "AttackTechniquePublic",
    "Component",
    "ComponentBase",
    "CveAttackMapping",
    "CveAttackMappingBase",
    "CveAttackMappingPublic",
    "Finding",
    "FindingAttackContext",
    "FindingAttackContextBase",
    "FindingAttackContextDetailPublic",
    "FindingAttackContextPublic",
    "FindingAttackMappingDetailPublic",
    "FindingAttackTechniqueDetailPublic",
    "FindingBase",
    "FindingDetailPublic",
    "FindingExplanationPublic",
    "FindingOccurrence",
    "FindingOccurrenceBase",
    "FindingOccurrencePublic",
    "FindingPublic",
    "FindingPriority",
    "FindingStatus",
    "FindingsPublic",
    "GovernanceRollupPublic",
    "GovernanceWaiverDebtEntryPublic",
    "GovernanceWaiverDebtPublic",
    "ImportParseErrorPublic",
    "MigrationStatus",
    "Project",
    "ProjectAttackSummaryPublic",
    "ProjectAttackTacticSummaryPublic",
    "ProjectAttackTechniqueSummaryPublic",
    "ProjectBase",
    "ProjectCreate",
    "ProjectCvssOnlyComparisonPublic",
    "ProjectDecisionSummaryPublic",
    "ProjectGovernanceRollupsPublic",
    "ProjectPublic",
    "ProjectsPublic",
    "ProjectUpdate",
    "ProviderSnapshot",
    "ProviderSnapshotBase",
    "ProviderSnapshotStatusPublic",
    "ProviderSourceStatusPublic",
    "ProviderStatusPublic",
    "ProviderUpdateJobPublic",
    "Report",
    "ReportBase",
    "ReportCreate",
    "ReportPublic",
    "ReportVerificationPublic",
    "ReportsPublic",
    "Token",
    "TokenPayload",
    "User",
    "UserBase",
    "UserPublic",
    "UsersPublic",
    "Vulnerability",
    "VulnerabilityBase",
    "Waiver",
    "WaiverBase",
    "WaiverCreate",
    "WaiverPublic",
    "WaiversPublic",
    "WaiverUpdate",
    "WorkbenchStatus",
    "import_table_models",
]
