from __future__ import annotations

import subprocess
from pathlib import Path

import pytest
from scripts import check_python_lock_exports as lock_check


@pytest.fixture
def lock_workspace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> tuple[Path, list[list[str]]]:
    (tmp_path / "backend").mkdir()
    for name in ("pyproject.toml", "backend/pyproject.toml", "uv.lock"):
        (tmp_path / name).write_text("fixture\n", encoding="utf-8")

    generated = b"# Generated by uv\ntransitive==1.2.3 \\\n    --hash=sha256:abc123\n"
    for name, _, _ in lock_check.EXPORTS:
        (tmp_path / name).write_bytes(generated)

    monkeypatch.setattr(
        lock_check.subprocess,
        "run",
        lambda argv, **_kwargs: subprocess.CompletedProcess(
            argv, 0, "uv 0.11.31 (test build)\n", ""
        ),
    )
    commands: list[list[str]] = []

    def run_uv(_uv: str, args: list[str], workspace: Path) -> None:
        commands.append(args)
        if args[0] == "export":
            name = args[args.index("--output-file") + 1]
            (workspace / name).write_bytes(generated)
        return None

    monkeypatch.setattr(lock_check, "_run_uv", run_uv)
    return tmp_path, commands


def test_lock_export_check_uses_pinned_offline_lock_and_both_export_profiles(
    lock_workspace: tuple[Path, list[list[str]]],
) -> None:
    root, commands = lock_workspace

    assert lock_check.check_python_lock_exports(root) == []
    assert commands[0] == ["lock", "--check", "--offline", "--python", "3.14", "--no-progress"]
    assert len(commands) == 3
    for command in commands[1:]:
        assert "--offline" in command
        assert "--locked" in command
        assert "--no-emit-project" in command
        assert "--no-emit-workspace" in command
    assert "--all-extras" in commands[1]
    assert "3.11" in commands[1]
    assert "--no-dev" in commands[2]
    assert "3.14" in commands[2]


@pytest.mark.parametrize("name", [item[0] for item in lock_check.EXPORTS])
def test_lock_export_check_rejects_modified_transitive_hash(
    lock_workspace: tuple[Path, list[list[str]]], name: str
) -> None:
    root, _ = lock_workspace
    committed = root / name
    committed.write_bytes(committed.read_bytes().replace(b"abc123", b"deadbeef"))

    failures = lock_check.check_python_lock_exports(root)

    assert len(failures) == 1
    assert failures[0].startswith(f"{name} differs from uv.lock export at line 3")


def test_lock_export_check_rejects_different_uv_version(
    lock_workspace: tuple[Path, list[list[str]]], monkeypatch: pytest.MonkeyPatch
) -> None:
    root, commands = lock_workspace
    monkeypatch.setattr(
        lock_check.subprocess,
        "run",
        lambda argv, **_kwargs: subprocess.CompletedProcess(argv, 0, "uv 0.11.32\n", ""),
    )

    assert lock_check.check_python_lock_exports(root) == [
        "python-lock-check requires uv 0.11.31, found 'uv 0.11.32'."
    ]
    assert commands == []
