from __future__ import annotations

from pathlib import Path

import pytest

from app.importers import (
    GenericOccurrenceCsvImporter,
    ImporterParseError,
    ImporterValidationError,
    build_importer_registry,
)

PROJECT_ROOT = Path(__file__).resolve().parents[3]
FIXTURE_DIR = PROJECT_ROOT / "data" / "input_fixtures"


def test_generic_occurrence_csv_importer_accepts_demo_fixture() -> None:
    importer = GenericOccurrenceCsvImporter()

    occurrences = importer.parse(
        (FIXTURE_DIR / "generic_occurrences.csv").read_text(encoding="utf-8"),
        filename="generic_occurrences.csv",
    )

    assert [
        (item.cve_id, item.target_ref, item.component_name, item.component_version)
        for item in occurrences
    ] == [
        ("CVE-2024-3094", "build-host-1", "xz", "5.6.0"),
        ("CVE-2024-4577", "web-tier", "php-cgi", "8.3.7"),
    ]
    assert occurrences[0].fix_version == "5.6.1-r2"
    assert occurrences[0].source == "trivy"
    assert occurrences[0].raw_evidence["raw_severity"] == "CRITICAL"
    assert occurrences[0].raw_evidence["purl"] == "pkg:apk/alpine/xz@5.6.0-r0"
    assert occurrences[0].raw_evidence["owner"] == "team-platform"
    assert occurrences[0].raw_evidence["business_service"] == "payments"
    assert occurrences[0].raw_evidence["unknown_columns"] == {
        "notes": "owner says, urgent",
        "ticket_url": "SEC-1001",
    }


def test_generic_occurrence_csv_importer_sniffs_semicolon_dialect() -> None:
    importer = GenericOccurrenceCsvImporter()

    occurrences = importer.parse(
        (FIXTURE_DIR / "generic_occurrences_semicolon.csv").read_text(encoding="utf-8"),
        filename="generic_occurrences_semicolon.csv",
    )

    assert [item.cve_id for item in occurrences] == ["CVE-2024-3094"]
    assert occurrences[0].source == "trivy"


def test_generic_occurrence_csv_importer_accepts_quoted_multiline_values() -> None:
    importer = GenericOccurrenceCsvImporter()

    occurrences = importer.parse(
        'cve_id,target_ref,notes\nCVE-2024-3094,build-host-1,"line one\nline two"\n',
        filename="generic.csv",
    )

    assert len(occurrences) == 1
    assert occurrences[0].target_ref == "build-host-1"
    assert occurrences[0].raw_evidence["line_number"] == 2
    assert occurrences[0].raw_evidence["unknown_columns"] == {"notes": "line one\nline two"}


def test_generic_occurrence_csv_importer_accepts_canonical_workbench_fields() -> None:
    importer = GenericOccurrenceCsvImporter()
    header = (
        "cve_id,target_ref,component_name,component_version,fix_versions,"
        + "raw_severity,owner,business_service,criticality,exposure,environment,"
        + "purl,package_type,source"
    )
    row = (
        "CVE-2022-22965,checkout-api,spring-webmvc,5.3.17,5.3.18,HIGH,"
        + "appsec,checkout,critical,public,prod,pkg:maven/spring-webmvc@5.3.17,"
        + "maven,spreadsheet"
    )

    occurrences = importer.parse(
        "\n".join([header, row]),
        filename="generic.csv",
    )

    assert len(occurrences) == 1
    occurrence = occurrences[0]
    assert occurrence.cve_id == "CVE-2022-22965"
    assert occurrence.target_ref == "checkout-api"
    assert occurrence.component_name == "spring-webmvc"
    assert occurrence.component_version == "5.3.17"
    assert occurrence.fix_version == "5.3.18"
    assert occurrence.raw_evidence["raw_severity"] == "HIGH"
    assert occurrence.raw_evidence["owner"] == "appsec"
    assert occurrence.raw_evidence["business_service"] == "checkout"
    assert occurrence.raw_evidence["criticality"] == "critical"
    assert occurrence.raw_evidence["exposure"] == "public"
    assert occurrence.raw_evidence["environment"] == "prod"
    assert occurrence.raw_evidence["purl"] == "pkg:maven/spring-webmvc@5.3.17"
    assert occurrence.raw_evidence["package_type"] == "maven"
    assert occurrence.source == "spreadsheet"


def test_generic_occurrence_csv_importer_rejects_removed_workbench_aliases() -> None:
    importer = GenericOccurrenceCsvImporter()
    header = (
        "vulnerability_id,asset_ref,component,installed_version,fixed_versions,"
        + "severity,asset_owner,service"
    )
    row = "CVE-2022-22965,checkout-api,spring-webmvc,5.3.17,5.3.18,HIGH,appsec,checkout"

    with pytest.raises(ImporterParseError, match="cve_id"):
        importer.parse("\n".join([header, row]), filename="generic.csv")


def test_generic_occurrence_csv_importer_accepts_comments_blanks_and_pipe_fix_versions() -> None:
    importer = GenericOccurrenceCsvImporter()

    occurrences = importer.parse(
        "\n".join(
            [
                "# generated by local scanner",
                "",
                "cve_id|target_ref|fix_versions",
                'CVE-2024-3094|build-host-1|"5.6.1-r2|5.6.2"',
            ]
        ),
        filename="generic",
    )

    assert len(occurrences) == 1
    assert occurrences[0].cve_id == "CVE-2024-3094"
    assert occurrences[0].fix_version == "5.6.1-r2"
    assert occurrences[0].raw_evidence["fix_versions"] == ["5.6.1-r2", "5.6.2"]


def test_generic_occurrence_csv_importer_collects_row_specific_errors() -> None:
    importer = GenericOccurrenceCsvImporter()

    with pytest.raises(ImporterParseError) as exc_info:
        importer.parse(
            (FIXTURE_DIR / "generic_occurrences_invalid.csv").read_text(encoding="utf-8"),
            filename="/private/tmp/generic_occurrences_invalid.csv",
        )

    message = str(exc_info.value)
    assert "line 2" in message
    assert "line 3" in message
    assert "not-a-cve" in message
    assert "/private/tmp" not in message


def test_generic_occurrence_csv_importer_requires_cve_id_column() -> None:
    importer = GenericOccurrenceCsvImporter()

    with pytest.raises(ImporterParseError, match="cve_id column"):
        importer.parse(
            (FIXTURE_DIR / "generic_occurrences_missing_cve.csv").read_text(encoding="utf-8"),
            filename="/private/tmp/generic_occurrences_missing_cve.csv",
        )


def test_generic_occurrence_csv_importer_rejects_invalid_boundary_payloads() -> None:
    importer = GenericOccurrenceCsvImporter()

    with pytest.raises(ImporterParseError, match="supports .csv"):
        importer.parse("cve_id\nCVE-2024-3094\n", filename="generic.json")

    with pytest.raises(ImporterParseError, match="UTF-8"):
        importer.parse(b"\xff\xfe", filename="generic.csv")

    with pytest.raises(ImporterValidationError, match="payload must be bytes or string"):
        importer.parse(object(), filename="generic.csv")  # type: ignore[arg-type]

    with pytest.raises(ImporterParseError, match="expected 1 columns, got 2"):
        importer.parse("cve_id\nCVE-2024-3094,extra\n", filename="generic.csv")

    with pytest.raises(ImporterParseError, match="missing a header row"):
        importer.parse("# comment only\n\n", filename="generic.csv")


def test_default_registry_uses_generic_occurrence_importer() -> None:
    registry = build_importer_registry()

    assert isinstance(registry.get("generic-occurrence-csv"), GenericOccurrenceCsvImporter)
    assert [
        item.cve_id
        for item in registry.parse(
            "generic-occurrence-csv",
            "cve_id,target_ref\nCVE-2024-3094,build-host-1\n",
            filename="generic.csv",
        )
    ] == ["CVE-2024-3094"]
