"""Check versioned agent guidance without running product tests or modifying it."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def metadata(path: Path) -> tuple[str, str]:
    """Read the single-line discovery fields used by this project's skills."""
    text = path.read_text(encoding="utf-8")
    header = re.match(r"\A---\n(.*?)\n---(?:\n|$)", text, re.S)
    if header is None:
        raise ValueError("missing YAML frontmatter")
    fields = {}
    for key in ("name", "description"):
        match = re.search(rf"^{key}:\s*([^\n]+)$", header[1], re.M)
        if match is None:
            raise ValueError(f"missing single-line {key}")
        fields[key] = match[1].strip().strip('"').strip("'")
    name, description = fields["name"], fields["description"]
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name) or len(name) > 64:
        raise ValueError("invalid skill name")
    if not description or len(description) > 1024 or any(c in description for c in "<>"):
        raise ValueError("invalid skill description")
    return name, description


def claude_loader(name: str, description: str) -> str:
    """Render a portable Claude loader; the actual guide has only one owner."""
    return (
        f"---\nname: {name}\ndescription: {description}\n---\n\n"
        "<!-- Generated by scripts/check_agent_skills.py --sync-claude. -->\n"
        f"Read [the shared guide](../../../.agents/skills/{name}/SKILL.md) "
        "for this workflow.\n"
    )


def check(root: Path, *, sync_claude: bool = False) -> list[str]:
    """Return actionable drift errors in discovery, references, and check routing."""
    failures: list[str] = []
    skills = sorted((root / ".agents/skills").glob("*/SKILL.md"))
    if not skills:
        failures.append("No canonical project skills found")
    names: set[str] = set()
    for path in skills:
        try:
            name, description = metadata(path)
        except ValueError as exc:
            failures.append(f"{path.relative_to(root)}: {exc}")
            continue
        if name != path.parent.name or name in names:
            failures.append(f"{path.relative_to(root)}: mismatched or duplicate skill name")
        names.add(name)
        loader = root / ".claude/skills" / name / "SKILL.md"
        expected = claude_loader(name, description)
        if sync_claude:
            loader.parent.mkdir(parents=True, exist_ok=True)
            loader.write_text(expected, encoding="utf-8")
        if not loader.is_file() or loader.read_text(encoding="utf-8") != expected:
            failures.append(f"{loader.relative_to(root)}: loader drift; run --sync-claude")

    for loader in (root / ".claude/skills").glob("vpw-*/SKILL.md"):
        if loader.parent.name not in names:
            failures.append(f"{loader.relative_to(root)}: orphaned project loader")

    targets = set(re.findall(r"^([A-Za-z0-9_-]+):", (root / "Makefile").read_text(), re.M))
    documents = [
        root / "AGENTS.md",
        root / "CLAUDE.md",
        root / ".agents/MAINTENANCE.md",
        *(root / ".agents/skills").rglob("*.md"),
        *(root / ".claude/skills").glob("vpw-*/SKILL.md"),
    ]
    for path in documents:
        if not path.is_file():
            failures.append(f"{path.relative_to(root)}: missing guidance file")
            continue
        text = path.read_text(encoding="utf-8")
        references = re.findall(r"\[[^\]\n]+\]\(([^)\n]+)\)", text)
        references += re.findall(r"^@([^\s]+)$", text, re.M)
        for reference in references:
            reference = reference.strip("<>").split("#", 1)[0]
            if not reference or re.match(r"[a-zA-Z][\w+.-]*:", reference):
                continue
            target = (path.parent / reference).resolve()
            if not target.is_relative_to(root.resolve()) or not target.exists():
                failures.append(f"{path.relative_to(root)}: broken local reference {reference}")
        commands = re.findall(r"`([^`\n]+)`", text)
        commands += re.findall(r"```[^\n]*\n(.*?)```", text, re.S)
        for command in commands:
            for target in re.findall(r"\bmake ([a-zA-Z][a-zA-Z0-9_-]*)\b", command):
                if target not in targets:
                    failures.append(f"{path.relative_to(root)}: unknown Make target {target}")

    # These are the two runner facts documented in check-selection.md.
    package = json.loads((root / "frontend/package.json").read_text(encoding="utf-8"))
    for key, command in {"test": "playwright test", "test:unit": "node --test"}.items():
        if command not in package.get("scripts", {}).get(key, ""):
            failures.append(f"frontend {key}: runner changed; review the check-selection guide")

    if (root / "CLAUDE.md").is_file():
        if (root / "CLAUDE.md").read_text(encoding="utf-8").strip() != "@AGENTS.md":
            failures.append("CLAUDE.md: keep shared project instructions in AGENTS.md")
    return failures


def main() -> int:
    """Check the current repository or explicitly refresh its generated loaders."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sync-claude", action="store_true", help="refresh generated Claude loaders"
    )
    args = parser.parse_args()
    failures = check(ROOT, sync_claude=args.sync_claude)
    for failure in failures:
        print(f"ERROR: {failure}")
    if failures:
        return 1
    count = len(list((ROOT / ".agents/skills").glob("*/SKILL.md")))
    print(
        f"Agent guidance OK: {count} skills, Claude loaders, local links, "
        "Make targets, test runners"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
