import type { FindingPublic } from "@/api-client"

export const DEMO_FINDINGS = [
  {
    id: "demo-f1",
    asset_id: "demo-asset-1",
    component_id: "demo-comp-1",
    cve_id: "CVE-2024-3400",
    priority: "critical",
    risk_score: 9.8,
    epss: 0.92,
    cvss_base_score: 10.0,
    in_kev: true,
    status: "open",
    component_name: "PAN-OS",
    component_purl: "pkg:rpm/panos@11.1.0",
    business_service: "payments-gateway",
    owner: "infra-team",
    exposure: "internet_facing",
    created_at: "2025-04-01T00:00:00Z",
    last_seen_at: "2025-04-30T10:00:00Z",
    rationale:
      "Exploited in the wild, CISA KEV entry, active ransomware campaigns targeting PAN-OS.",
    recommended_action: "Patch immediately to PAN-OS 11.1.2-h3.",
  },
  {
    id: "demo-f2",
    asset_id: "demo-asset-2",
    component_id: "demo-comp-2",
    cve_id: "CVE-2024-21887",
    priority: "critical",
    risk_score: 9.1,
    epss: 0.88,
    cvss_base_score: 9.1,
    in_kev: true,
    status: "open",
    component_name: "Ivanti Connect Secure",
    component_purl: "pkg:generic/ivanti-connect@22.3.3",
    business_service: "vpn-service",
    owner: "network-team",
    exposure: "internet_facing",
    created_at: "2025-04-02T00:00:00Z",
    last_seen_at: "2025-04-29T09:00:00Z",
    rationale:
      "Command injection in web component, mass exploitation observed.",
    recommended_action:
      "Apply Ivanti patch and run factory reset per vendor advisory.",
  },
  {
    id: "demo-f3",
    asset_id: "demo-asset-3",
    component_id: "demo-comp-3",
    cve_id: "CVE-2024-1709",
    priority: "critical",
    risk_score: 9.4,
    epss: 0.95,
    cvss_base_score: 10.0,
    in_kev: false,
    status: "in_review",
    component_name: "ConnectWise ScreenConnect",
    component_purl: "pkg:generic/screenconnect@23.9.7",
    business_service: "internal-tools",
    owner: "it-team",
    exposure: "internal",
    created_at: "2025-04-03T00:00:00Z",
    last_seen_at: "2025-04-27T11:00:00Z",
    rationale:
      "Auth bypass with EPSS > 0.95 — exploitation probability is very high.",
    recommended_action: "Upgrade to ScreenConnect 23.9.8 immediately.",
  },
  {
    id: "demo-f4",
    asset_id: "demo-asset-4",
    component_id: "demo-comp-4",
    cve_id: "CVE-2023-4966",
    priority: "critical",
    risk_score: 8.9,
    epss: 0.87,
    cvss_base_score: 9.4,
    in_kev: true,
    status: "open",
    component_name: "Citrix NetScaler",
    component_purl: "pkg:generic/netscaler@13.1",
    business_service: "load-balancer",
    owner: "platform-team",
    exposure: "internet_facing",
    created_at: "2025-04-04T00:00:00Z",
    last_seen_at: "2025-04-26T08:00:00Z",
    rationale:
      "Citrix Bleed — session token leak, KEV entry, active exploitation.",
    recommended_action: "Apply Citrix security bulletin CTX579459.",
  },
  {
    id: "demo-f5",
    asset_id: "demo-asset-5",
    component_id: "demo-comp-5",
    cve_id: "CVE-2023-44487",
    priority: "high",
    risk_score: 7.5,
    epss: 0.71,
    cvss_base_score: 7.5,
    in_kev: true,
    status: "open",
    component_name: "nginx",
    component_purl: "pkg:deb/nginx@1.18.0",
    business_service: "api-gateway",
    owner: "platform-team",
    exposure: "internet_facing",
    created_at: "2025-04-05T00:00:00Z",
    last_seen_at: "2025-04-28T14:00:00Z",
    rationale: "HTTP/2 Rapid Reset DoS, actively exploited.",
    recommended_action: "Upgrade nginx to 1.24.0 or later.",
  },
  {
    id: "demo-f6",
    asset_id: "demo-asset-6",
    component_id: "demo-comp-6",
    cve_id: "CVE-2024-27198",
    priority: "high",
    risk_score: 7.8,
    epss: 0.73,
    cvss_base_score: 9.8,
    in_kev: false,
    status: "open",
    component_name: "JetBrains TeamCity",
    component_purl: "pkg:generic/teamcity@2023.11.3",
    business_service: "ci-cd-pipeline",
    owner: "devops-team",
    exposure: "internal",
    created_at: "2025-04-06T00:00:00Z",
    last_seen_at: "2025-04-25T16:00:00Z",
    rationale:
      "Auth bypass in TeamCity server, high EPSS exploitation signal.",
    recommended_action: "Upgrade to TeamCity 2023.11.4.",
  },
  {
    id: "demo-f7",
    asset_id: "demo-asset-7",
    component_id: "demo-comp-7",
    cve_id: "CVE-2023-46805",
    priority: "high",
    risk_score: 6.9,
    epss: 0.64,
    cvss_base_score: 8.2,
    in_kev: true,
    status: "remediating",
    component_name: "Ivanti Policy Secure",
    component_purl: "pkg:generic/ivanti-policy@22.3",
    business_service: "vpn-service",
    owner: "network-team",
    exposure: "internet_facing",
    created_at: "2025-04-07T00:00:00Z",
    last_seen_at: "2025-04-24T10:00:00Z",
    rationale:
      "KEV entry, pairs with CVE-2024-21887 for chained exploitation.",
    recommended_action:
      "Remediation in progress — verify patch application.",
  },
  {
    id: "demo-f8",
    asset_id: "demo-asset-8",
    component_id: "demo-comp-8",
    cve_id: "CVE-2024-3094",
    priority: "high",
    risk_score: 6.5,
    epss: 0.61,
    cvss_base_score: 10.0,
    in_kev: false,
    status: "open",
    component_name: "xz-utils",
    component_purl: "pkg:deb/xz-utils@5.6.0",
    business_service: "platform-infra",
    owner: "platform-team",
    exposure: "internal",
    created_at: "2025-04-08T00:00:00Z",
    last_seen_at: "2025-04-23T12:00:00Z",
    rationale: "XZ backdoor in liblzma — supply chain compromise.",
    recommended_action:
      "Downgrade to xz-utils 5.4.x and rebuild affected containers.",
  },
  {
    id: "demo-f9",
    asset_id: "demo-asset-9",
    component_id: "demo-comp-9",
    cve_id: "CVE-2024-21413",
    priority: "medium",
    risk_score: 5.2,
    epss: 0.42,
    cvss_base_score: 9.8,
    in_kev: false,
    status: "open",
    component_name: "Microsoft Outlook",
    component_purl: "pkg:generic/outlook@2021",
    business_service: "collaboration",
    owner: "it-team",
    exposure: "internal",
    created_at: "2025-04-09T00:00:00Z",
    last_seen_at: "2025-04-22T09:00:00Z",
    rationale:
      "Moniker link bypass — critical CVSS but lower operational EPSS.",
    recommended_action: "Apply February 2024 Patch Tuesday update.",
  },
  {
    id: "demo-f10",
    asset_id: "demo-asset-10",
    component_id: "demo-comp-10",
    cve_id: "CVE-2023-36884",
    priority: "medium",
    risk_score: 4.8,
    epss: 0.38,
    cvss_base_score: 8.3,
    in_kev: true,
    status: "waived",
    component_name: "Microsoft Office",
    component_purl: "pkg:generic/office@2021",
    business_service: "collaboration",
    owner: "it-team",
    exposure: "internal",
    created_at: "2025-04-10T00:00:00Z",
    last_seen_at: "2025-04-21T14:00:00Z",
    rationale:
      "Office HTML injection — waived pending compensating control review.",
    recommended_action: "Apply KB5028185 when waiver expires.",
  },
] as unknown as FindingPublic[]
