import { DEMO_PROJECT_ID } from "./demo-data-project.ts"

export const DEMO_REPORTS = [
  {
    id: "__demo__report-001",
    analysis_run_id: "demo-run-0001",
    content_type: "text/html",
    created_at: "2025-04-30T08:12:00Z",
    download_url: "#demo-download",
    filename: "vpw-evidence-2025-04-30-executive.html",
    format: "html",
    kind: "report",
    project_id: DEMO_PROJECT_ID,
    sha256: "demo-only-not-a-real-checksum",
    size_bytes: 84231,
    metadata_json: undefined,
  },
  {
    id: "__demo__report-002",
    analysis_run_id: "demo-run-0001",
    content_type: "text/markdown",
    created_at: "2025-04-30T08:11:00Z",
    download_url: "#demo-download",
    filename: "vpw-evidence-2025-04-30-technical.md",
    format: "markdown",
    kind: "report",
    project_id: DEMO_PROJECT_ID,
    sha256: "demo-only-not-a-real-checksum",
    size_bytes: 32109,
    metadata_json: undefined,
  },
  {
    id: "__demo__report-003",
    analysis_run_id: "demo-run-0001",
    content_type: "application/json",
    created_at: "2025-04-30T08:11:30Z",
    download_url: "#demo-download",
    filename: "vpw-evidence-2025-04-30-findings.json",
    format: "json",
    kind: "report",
    project_id: DEMO_PROJECT_ID,
    sha256: "demo-only-not-a-real-checksum",
    size_bytes: 156023,
    metadata_json: undefined,
  },
  {
    id: "__demo__report-004",
    analysis_run_id: "demo-run-0001",
    content_type: "application/zip",
    created_at: "2025-04-30T08:13:00Z",
    download_url: "#demo-download",
    filename: "vpw-evidence-bundle-2025-04-30.zip",
    format: "zip",
    kind: "report",
    project_id: DEMO_PROJECT_ID,
    sha256: "demo-only-not-a-real-checksum",
    size_bytes: 312456,
    metadata_json: undefined,
  },
]
