import type { FindingPublic, FindingStatus } from "@/api-client"

import { DEMO_PROJECT_ID } from "./demo-data-project.ts"

type DemoFindingSeed = readonly [
  string,
  string,
  string,
  "critical" | "high" | "medium",
  number,
  number,
  number,
  boolean,
  FindingStatus,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
]

const generatedAt = "2026-04-29T12:00:00Z"

const rows: readonly DemoFindingSeed[] = [
  ["demo-f1", "pay-api-01", "CVE-2022-22965", "critical", 9.7, 0.94428, 9.8, true, "open", "spring-webmvc", "5.3.17", "pkg:maven/org.springframework/spring-webmvc@5.3.17", "payments", "team-payments", "critical", "internet-facing", "production", "Upgrade Spring to 5.3.18 and validate servlet exposure.", "KEV-backed Spring framework exposure on an internet-facing production API."],
  ["demo-f2", "pay-api-01", "CVE-2021-44228", "critical", 9.9, 0.94465, 10, true, "open", "log4j-core", "2.14.1", "pkg:maven/org.apache.logging.log4j/log4j-core@2.14.1", "payments", "team-payments", "critical", "internet-facing", "production", "Upgrade Log4j to 2.17.2 and re-import validation evidence.", "Log4Shell is KEV-backed, high EPSS, and present on a critical payment API."],
  ["demo-f3", "pay-ci-01", "CVE-2024-3094", "critical", 9.1, 0.84588, 10, false, "remediating", "xz", "5.6.0-r0", "pkg:apk/alpine/xz@5.6.0-r0", "payments", "team-platform", "high", "internal", "production", "Rebuild the base image from a clean xz package and attach build evidence.", "High CVSS supply-chain finding in production CI support infrastructure."],
  ["demo-f4", "checkout-web-01", "CVE-2024-4577", "critical", 9.6, 0.94393, 9.8, true, "open", "php-cgi", "8.3.7", "pkg:generic/php-cgi@8.3.7", "checkout", "team-checkout", "critical", "internet-facing", "production", "Upgrade PHP CGI to 8.3.8 and confirm locale exposure is removed.", "PHP CGI exposure is KEV-backed and reachable from the checkout edge."],
  ["demo-f5", "checkout-web-01", "CVE-2023-44487", "high", 8.2, 0.94446, 7.5, true, "open", "envoy", "1.26.1", "pkg:generic/envoy@1.26.1", "checkout", "team-checkout", "critical", "internet-facing", "production", "Upgrade Envoy and verify upstream rate limiting telemetry.", "Open internet-facing HTTP/2 edge path has KEV and high EPSS signals for checkout availability."],
  ["demo-f6", "checkout-web-02", "CVE-2024-4577", "critical", 8.8, 0.94393, 9.8, true, "open", "php-cgi", "8.2.20", "pkg:generic/php-cgi@8.2.20", "checkout", "team-checkout", "high", "dmz", "production", "Upgrade PHP CGI to 8.2.21 and validate DMZ exposure.", "Secondary checkout node remains in the same KEV-backed PHP campaign."],
  ["demo-f7", "id-dc-01", "CVE-2020-1472", "critical", 9.2, 0.9438, 5.5, true, "open", "windows-netlogon", "2019", "pkg:generic/windows-netlogon@2019", "identity", "team-identity", "critical", "internal", "production", "Apply the Netlogon hardening update and confirm domain-controller enforcement.", "KEV-backed identity finding remains open on production domain-controller infrastructure."],
  ["demo-f8", "id-dc-02", "CVE-2020-1472", "critical", 7.2, 0.9438, 5.5, true, "accepted", "windows-netlogon", "2016", "pkg:generic/windows-netlogon@2016", "identity", "team-identity", "high", "internal", "production", "Keep compensating controls active until the approved maintenance window.", "Accepted risk is time-boxed for a legacy domain controller."],
  ["demo-f9", "id-admin-01", "CVE-2021-44228", "critical", 8.4, 0.94465, 10, true, "open", "log4j-core", "2.13.3", "pkg:maven/org.apache.logging.log4j/log4j-core@2.13.3", "identity", "team-identity", "high", "internal", "production", "Upgrade Log4j and validate identity admin telemetry after redeploy.", "Log4Shell remains open on an internal identity admin console."],
  ["demo-f10", "file-transfer-01", "CVE-2023-34362", "critical", 9.4, 0.94254, 9.8, true, "open", "moveit-transfer", "2023.0.0", "pkg:pypi/moveit-transfer@2023.0.0", "file-transfer", "team-platform", "critical", "dmz", "production", "Upgrade MOVEit Transfer to 2023.0.2 and validate partner upload logs.", "Managed file-transfer exposure is KEV-backed and DMZ reachable."],
  ["demo-f11", "file-transfer-dr-01", "CVE-2023-34362", "high", 5.8, 0.94254, 9.8, true, "suppressed", "moveit-transfer", "2023.0.1", "pkg:pypi/moveit-transfer@2023.0.1", "file-transfer", "team-platform", "high", "internal", "production", "Retain VEX not-affected evidence and review if the DR node is re-enabled.", "VEX suppression needs evidence review if the DR upload path is re-enabled."],
  ["demo-f12", "catalog-api-01", "CVE-2022-22965", "critical", 8.9, 0.94428, 9.8, true, "open", "spring-webmvc", "5.3.15", "pkg:maven/org.springframework/spring-webmvc@5.3.15", "catalog", "team-catalog", "high", "internal", "production", "Upgrade Spring MVC to 5.3.18 and rerun container evidence.", "Open Spring campaign finding remains on a production catalog API with high EPSS."],
  ["demo-f13", "catalog-api-01", "CVE-2021-44228", "critical", 8.6, 0.94465, 10, true, "open", "log4j-core", "2.12.1", "pkg:maven/org.apache.logging.log4j/log4j-core@2.12.1", "catalog", "team-catalog", "high", "internal", "production", "Upgrade Log4j to 2.17.2 and attach validation evidence.", "Open Log4Shell finding in a high-criticality catalog service."],
  ["demo-f14", "catalog-api-02", "CVE-2022-22965", "high", 6.7, 0.94428, 9.8, true, "in_review", "spring-webflux", "5.3.16", "pkg:maven/org.springframework/spring-webflux@5.3.16", "catalog", "team-catalog", "medium", "internal", "staging", "Confirm staging exposure and patch before next promotion.", "Staging Spring finding needs owner review before production promotion."],
  ["demo-f15", "warehouse-api-01", "CVE-2021-44228", "critical", 8.1, 0.94465, 10, true, "open", "log4j-core", "2.14.1", "pkg:maven/org.apache.logging.log4j/log4j-core@2.14.1", "fulfillment", "team-fulfillment", "high", "internal", "production", "Upgrade Log4j and validate fulfillment worker telemetry.", "Fulfillment runtime remains in the Log4Shell campaign."],
  ["demo-f16", "edge-cache-01", "CVE-2023-44487", "high", 7.9, 0.94446, 7.5, true, "open", "nginx", "1.25.1", "pkg:generic/nginx@1.25.1", "edge", "team-edge", "high", "internet-facing", "production", "Upgrade nginx and verify CDN mitigation telemetry.", "Open internet-facing HTTP/2 edge cache carries KEV and high EPSS availability risk."],
  ["demo-f17", "edge-cache-02", "CVE-2023-44487", "high", 5.9, 0.94446, 7.5, true, "accepted", "envoy", "1.25.0", "pkg:generic/envoy@1.25.0", "edge", "team-edge", "high", "internet-facing", "production", "Keep waiver review due today and validate upstream mitigation.", "Accepted risk is review due for an edge HTTP/2 finding."],
  ["demo-f18", "analytics-etl-01", "CVE-2021-44228", "medium", 2.9, 0.94465, 10, true, "fixed", "log4j-core", "2.17.2", "pkg:maven/org.apache.logging.log4j/log4j-core@2.17.2", "analytics", "team-data", "medium", "internal", "production", "Retain fixed evidence in the bundle and suppress stale finding noise.", "Fixed evidence is retained for audit continuity."],
  ["demo-f19", "analytics-notebook-01", "CVE-2024-3094", "high", 4.9, 0.84588, 10, false, "accepted", "xz", "5.6.0-r0", "pkg:apk/alpine/xz@5.6.0-r0", "analytics", "team-data", "low", "internal", "development", "Rebuild the notebook image after active experiments finish.", "Developer notebook risk is accepted with a time-boxed owner decision."],
  ["demo-f20", "backoffice-01", "CVE-2024-4577", "high", 6.5, 0.94393, 9.8, true, "in_review", "php-cgi", "8.1.28", "pkg:generic/php-cgi@8.1.28", "backoffice", "team-corporate", "medium", "internal", "production", "Confirm locale and CGI exposure before closing or escalating.", "OpenVEX marks the backoffice PHP finding under investigation."],
  ["demo-f21", "order-api-01", "CVE-2022-22965", "critical", 9.0, 0.94428, 9.8, true, "open", "spring-webmvc", "5.3.16", "pkg:maven/org.springframework/spring-webmvc@5.3.16", "orders", "team-orders", "high", "internet-facing", "production", "Upgrade Spring MVC and validate order API regression evidence.", "Open internet-facing order API remains in the KEV-backed Spring campaign."],
  ["demo-f22", "order-worker-01", "CVE-2021-44228", "critical", 8.0, 0.94465, 10, true, "remediating", "log4j-core", "2.14.1", "pkg:maven/org.apache.logging.log4j/log4j-core@2.14.1", "orders", "team-orders", "high", "internal", "production", "Complete Log4j upgrade and attach post-deploy validation evidence.", "Remediation is in progress for high-EPSS Log4Shell on the production order worker."],
  ["demo-f23", "vendor-portal-01", "CVE-2023-34362", "critical", 9.1, 0.94254, 9.8, true, "open", "moveit-transfer", "2023.0.0", "pkg:pypi/moveit-transfer@2023.0.0", "partner-portal", "team-partner", "high", "dmz", "production", "Upgrade MOVEit Transfer and review partner upload audit logs.", "Partner upload path is DMZ reachable and KEV-backed."],
  ["demo-f24", "build-host-1", "CVE-2024-3094", "critical", 8.7, 0.84588, 10, false, "open", "xz", "5.6.0-r0", "pkg:apk/alpine/xz@5.6.0-r0", "ci-platform", "team-platform", "high", "internal", "production", "Rebuild the host image from trusted source mirrors.", "Build host supply-chain exposure remains open and unmapped to ATT&CK."],
]

const mappedCves = new Set([
  "CVE-2020-1472",
  "CVE-2021-44228",
  "CVE-2022-22965",
  "CVE-2023-34362",
  "CVE-2023-44487",
  "CVE-2024-4577",
])

export const DEMO_FINDINGS = rows.map(
  ([
    id,
    assetKey,
    cveId,
    priority,
    riskScore,
    epss,
    cvss,
    inKev,
    status,
    componentName,
    componentVersion,
    purl,
    businessService,
    owner,
    criticality,
    exposure,
    environment,
    recommendedAction,
    rationale,
  ], index) => ({
    asset_criticality: criticality,
    asset_environment: environment,
    asset_id: `demo-asset-${index + 1}`,
    asset_key: assetKey,
    asset_name: assetKey,
    asset_target_ref: `${environment}:${assetKey}`,
    attack_mapped: mappedCves.has(cveId),
    business_service: businessService,
    component_id: `demo-component-${index + 1}`,
    component_name: componentName,
    component_purl: purl,
    component_version: componentVersion,
    created_at: generatedAt,
    cve_id: cveId,
    cvss_base_score: cvss,
    epss,
    exposure,
    first_seen_at: "2026-04-21T12:00:00Z",
    id,
    in_kev: inKev,
    last_seen_at: generatedAt,
    operational_rank: index + 1,
    owner,
    priority,
    priority_rank: index + 1,
    project_id: DEMO_PROJECT_ID,
    rationale,
    recommended_action: recommendedAction,
    risk_score: riskScore,
    status,
    suppressed_by_vex: status === "suppressed",
    under_investigation: status === "in_review" && cveId === "CVE-2024-4577",
    updated_at: generatedAt,
    vulnerability_id: cveId,
    waived: status === "accepted",
  }),
) as unknown as FindingPublic[]
