import type {
  GovernanceWaiverDebtEntryPublic,
  ProjectGovernanceRollupsPublic,
  WaiverPublic,
} from "@/api-client"

import { DEMO_PROJECT_ID } from "./demo-data-project.ts"

export const DEMO_WAIVERS = [
  {
    approval_ref: "DEMO-RISK-1001",
    asset_id: null,
    asset_key: "id-dc-02",
    created_at: "2026-04-21T12:00:00Z",
    cve_id: "CVE-2020-1472",
    days_remaining: 90,
    expires_at: "2026-07-28",
    finding_id: "demo-f8",
    id: "demo-waiver-1001",
    matched_findings: 1,
    owner: "identity-risk",
    project_id: DEMO_PROJECT_ID,
    reason: "Legacy domain controller isolated behind compensating controls until the approved maintenance window.",
    review_at: "2026-05-28",
    service: "identity",
    status: "active",
    ticket_url: null,
    updated_at: "2026-04-29T12:00:00Z",
  },
  {
    approval_ref: "DEMO-RISK-1002",
    asset_id: null,
    asset_key: "edge-cache-02",
    created_at: "2026-04-21T12:00:00Z",
    cve_id: "CVE-2023-44487",
    days_remaining: 10,
    expires_at: "2026-05-08",
    finding_id: "demo-f17",
    id: "demo-waiver-1002",
    matched_findings: 1,
    owner: "edge-platform",
    project_id: DEMO_PROJECT_ID,
    reason: "Upstream CDN rate limiting is active while the edge runtime is replaced.",
    review_at: "2026-04-29",
    service: "edge",
    status: "review_due",
    ticket_url: null,
    updated_at: "2026-04-29T12:00:00Z",
  },
  {
    approval_ref: "DEMO-RISK-1003",
    asset_id: null,
    asset_key: "analytics-notebook-01",
    created_at: "2026-04-21T12:00:00Z",
    cve_id: "CVE-2024-3094",
    days_remaining: 60,
    expires_at: "2026-06-27",
    finding_id: "demo-f19",
    id: "demo-waiver-1003",
    matched_findings: 1,
    owner: "data-platform",
    project_id: DEMO_PROJECT_ID,
    reason: "Developer notebook is isolated from production paths and queued for image rebuild.",
    review_at: "2026-05-20",
    service: "analytics",
    status: "active",
    ticket_url: null,
    updated_at: "2026-04-29T12:00:00Z",
  },
  {
    approval_ref: "DEMO-RISK-1004",
    asset_id: null,
    asset_key: "build-host-1",
    created_at: "2026-04-21T12:00:00Z",
    cve_id: "CVE-2024-3094",
    days_remaining: 45,
    expires_at: "2026-06-12",
    finding_id: "demo-f24",
    id: "demo-waiver-1004",
    matched_findings: 1,
    owner: "platform-security",
    project_id: DEMO_PROJECT_ID,
    reason: "Build host is quarantined to signed internal mirrors while the base image rebuild completes.",
    review_at: "2026-05-13",
    service: "ci-platform",
    status: "active",
    ticket_url: null,
    updated_at: "2026-04-29T12:00:00Z",
  },
] as unknown as WaiverPublic[]

const waiverDebtItems = DEMO_WAIVERS.map((waiver) => ({
  asset_key: waiver.asset_key,
  cve_id: waiver.cve_id,
  days_remaining: waiver.days_remaining,
  expires_at: waiver.expires_at,
  finding_id: waiver.finding_id,
  id: waiver.id,
  matched_findings: waiver.matched_findings,
  owner: waiver.owner,
  review_at: waiver.review_at,
  scope: waiver.asset_key ? `asset:${waiver.asset_key}` : "project",
  service: waiver.service,
  status: waiver.status,
})) as unknown as GovernanceWaiverDebtEntryPublic[]

export const DEMO_GOVERNANCE_ROLLUPS = {
  project_id: DEMO_PROJECT_ID,
  waiver_debt: {
    accepted_finding_count: 4,
    active_count: 3,
    expired_count: 0,
    expiring_soon_count: 1,
    items: waiverDebtItems,
    matched_finding_count: 4,
    review_due_count: 1,
    waiver_count: 4,
  },
} as unknown as ProjectGovernanceRollupsPublic
